require("launch")
require("configs.options")
require("configs.keymaps")
require("configs.autocmds")
spec("plugins.colorscheme")
spec("plugins.lualine")
spec("plugins.treesitter")
spec("plugins.mason")
spec("plugins.whichkey")
spec("plugins.showkeys")
-- spec("plugins.nvimtree")
spec("plugins.oil")
spec("plugins.blink-cmp")
spec("plugins.lspconfig")
--spec("plugins.cmp")
spec("plugins.none-ls")
-- spec("plugins.telescope")
spec("plugins.fzf")
spec("plugins.autopairs")
spec("plugins.navic")
spec("plugins.breadcrumbs")
spec("plugins.comment")
spec("plugins.illuminate")
spec("plugins.indentline")
spec("plugins.colorizer")
spec("plugins.tmux-navigator")
require("configs.lazy")
