require("asif.launch")
require("asif.configs.options")
require("asif.configs.keymaps")
require("asif.configs.autocmds")
spec("asif.plugins.colorscheme")
spec("asif.plugins.lualine")
spec("asif.plugins.treesitter")
spec("asif.plugins.mason")
spec("asif.plugins.whichkey")
spec("asif.plugins.showkeys")
-- spec("asif.plugins.nvimtree")
spec("asif.plugins.oil")
spec("asif.plugins.blink-cmp")
spec("asif.plugins.lspconfig")
--spec("asif.plugins.cmp")
spec("asif.plugins.none-ls")
-- spec("asif.plugins.telescope")
spec("asif.plugins.fzf")
spec("asif.plugins.autopairs")
spec("asif.plugins.navic")
spec("asif.plugins.breadcrumbs")
spec("asif.plugins.comment")
spec("asif.plugins.illuminate")
spec("asif.plugins.indentline")
spec("asif.plugins.colorizer")
spec("asif.plugins.tmux-navigator")
require("asif.configs.lazy")
